language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2

install:
  - composer install

script:
  - emoji_support/vendor/bin/parallel-lint --exclude emoji_support/vendor .

before_deploy:
  - rm -rf emoji_support/vendor
  - zip -r 'Emoji Support' emoji_support

deploy:
  provider: releases
  api_key:
    secure: nnuzgzytEYhdxXEersoWkP7YXsl9cZAsEdVnJB4IUgs99fF0DNqivFFlDL0Nm9QibbGyvjjqkJvGA3CVSA4zbv2EzKTJk3OAP5D8/iRGWog0V9kSbG6O8Zcmf7OGJhs1TonVRSxcseAebf8xlY0iudEbb5okTZEEqLJfPH8kaXChs2oqP6lcUe2gw4BSnt6AgwkFnt4ZCzpooO4Pd1frOYt/P4XKPAWWDnPxswQf928YvVJRCT/Kp5wZ4hcxQIENDnCjlHxUL8NHtCiS7UiUJQeJLLIwN+2cqFGvCSEPzovpPumkrvIgWFKLKjPXw+BM9eQuQUFa+vvFvHGT0Z2BVH0PR55/LhmDSjKwrtwgbTbAdTX/WjOOfwTUEvu/vdqYICkbLc+CBV0kYFgW4AKAtMAigCJmhYYIRM4Bqi/jAYSkCjB+r6bUHhHNnOpry08LVcjSfCQ+ykKVaM2jIcWCCT/5F9BT/ssPumodSaQO+Zm7G3h5CAcyxRNAIIv+4los60Pvg4VwxxAraAM2IdnkW8sl+80/XA1pbsHYc9YDeVRVLuyAIdSuw2JDxvNH3Lsa6jy2tRc6jPErGyR7K9LzWszQegISO/rb0E7+4Ly+1CjSuyEOvO4NulI+kiqaVb4nKn/Jxmwfj04C5pkXO79EqraLb68PIR4dBcU16bwWKXY=
  file: "Emoji Support.zip"
  skip_cleanup: true
  on:
    php: 7.2
    tags: true
    condition: $TRAVIS_PULL_REQUEST = false
    repo: ExpressionEngine/Emoji-Support
